### ISSUE TITLE
Apex Cloud Functions seems to be down

### ISSUE THREAD

**Issue by omar2205** [CSS-Tricks/serverless#118]
![apex logo](https://serverless.css-tricks.com/images/apex.png)
apex.run seems down, gives `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by chriscoyier** [comment]
Confirmed. I don't know of any news about them off hand. Maybe we'll wait a couple of days and if its still dead, remove it.

**Comment by justDMNK** [comment]
Can be closed @chriscoyier
