### ISSUE TITLE
Sidebar overflows and is unscrollable on iPad

### ISSUE THREAD

**Issue by cbirdsong** [CSS-Tricks/serverless#146]
Hi! Just noticed the number of items in the sidebar is too tall for the iPad, and it’s seemingly unable to be scrolled.

![IMG_0015](https://user-images.githubusercontent.com/1672206/100461672-bed43680-308e-11eb-9865-f7b809454839.png)

This is likely a pretty easy fix, maybe with a height-based media query to toggle on overflow-scroll?

**Comment by chriscoyier** [comment]
Pushed a simplification to how all this is handled, hopefully it's scrollable now

**Comment by cbirdsong** [comment]
👍 It no longer overflows at the default text size (at least on my device size), and appears to handle things well enough once zoomed.
