### ISSUE TITLE
Cards display "external site link" arrow in top right corner, however links open in the same tab

### ISSUE THREAD

**Issue by denno020** [CSS-Tricks/serverless#158]
![image](https://user-images.githubusercontent.com/2059313/113376801-1aeef480-93ba-11eb-9f57-c84102961fb0.png)

To me, the arrow in the top right corner of the card indicates that the link will open in a new tab, however it doesn't.

This may very well be a non-issue, so feel free to close this if the link isn't supposed to open in a new tab, just wanted to point it out in case it is supposed to.

**Comment by chriscoyier** [comment]
Hey I could totally see how the affordance of an up-and-to-the-right arrow begs for opening in a new tab. I don't want to actually do that though. My opinions on that are here: https://css-tricks.com/use-target_blank/

But... Maybe then the icon should change? Maybe like a chain link emoji or something?

**Comment by denno020** [comment]
Hey Chris, interesting read. I personally would fall into the category of wanting these links to open in a new tab from a normal click, because this site specifically is a list of available services that people are going to peruse. It's highly unlikely that the first service I click on is the exact one that I'm going to want - I could very well want to look through a few of these services, and always have the flexibility to just close the new tab when I've decided against one of the services, rather than figure out how many times I have to press back to get back to the list of other services available.

That's just my opinion :).

Anyway, opinions aside, I definitely think it would help the affordance of the cards if the icon was different. I feel like a chain link emoji in the top right might be a bit awkward, but it would at least give a better idea of what is going to happen when clicking on the link.

I'm more than happy to leave the decision up to you - as I mentioned earlier, I only wanted to point this out in case they were supposed to open in a new tab :).
