### ISSUE TITLE
Site breaks after navigation, service-worker issue

### ISSUE THREAD

**Issue by IanVS** [CSS-Tricks/serverless#184]
Something strange is going on. On the production page (https://serverless.css-tricks.com/), If I hard-refresh the page, I see content, but if I try to navigate to any of the other pages using the right-nav, I see 404s in the console and the page does not load up.  Refreshing does not solve, only a hard-refresh without cache.  It appears to be a service-worker issue, because when I unregister it, the page works just fine.

**Comment by IanVS** [comment]
Oh I wonder if this is a leftover from gatsby.  I visited the site prior to the conversion to astro, and probably got the SW loaded at that time.  After unregistering it, I'm no longer getting the SW installed.

**Comment by chriscoyier** [comment]
Gonna try this
https://github.com/CSS-Tricks/serverless/commit/98c8abd23857f0ce52f63601ca31d699b0310321

I think that shoulllllld do it.

**Comment by IanVS** [comment]
Seems reasonable 👍 

If you haven't seen it before, this could be a good use case for https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md.
