### ISSUE TITLE
Site not rendering

### ISSUE THREAD

**Issue by uguareschi** [CSS-Tricks/serverless#188]
<img width="1440" alt="Screenshot 2021-12-14 at 15 37 42" src="https://user-images.githubusercontent.com/21092021/146059437-cb43769a-ba2f-450f-b298-c42edaf48c66.png">

**Comment by chriscoyier** [comment]
Can you shift-refresh and let me know if that works?

**Comment by uguareschi** [comment]
> Can you shift-refresh and let me know if that works?

Yep that worked
