### ISSUE TITLE
CONTENT add a bunch of resources

### ISSUE THREAD

**Issue by AndreaMinato** [CSS-Tricks/serverless#23]
Hi, I would like to add some resources that I didn't found on the site yet.

### Static site generators
 - [Gridsome](https://gridsome.org/)

### Notifications
- [Firebase cloud messaging](https://firebase.google.com/docs/cloud-messaging)

### Forms
- [Netlify forms](https://www.netlify.com/docs/form-handling/)
- [Field goal](https://fieldgoal.io/)

### Hosting
- [Azure blob storage](https://azure.microsoft.com/en-us/services/storage/blobs/)

### Media
- [Azure blob storage](https://azure.microsoft.com/en-us/services/storage/blobs/)
- [Firebase cloud storage](https://firebase.google.com/docs/storage/web/start)

### Uncategorized
- [Stackbit](https://www.stackbit.com/)

Please let me know if I could start some PR to add them and how you would like me to work on them.

**Comment by chriscoyier** [comment]
These are all awesome ideas! Feel free to PR any and all of them. I'd probably toss Stackbit into the SSG category, even though I know it's a bit of a meta thing on top of those. That can be explained in text.
