### ISSUE TITLE
Couple'a missing images

### ISSUE THREAD

**Issue by alexzaworski** [CSS-Tricks/serverless#64]
Howdy,

The logos for AppSync (used [here](https://github.com/CSS-Tricks/serverless/blob/0cf3b23efdea5cc3f18ee25e87d9f5626990ac08/src/content/data/appsync.md) and [here](https://github.com/CSS-Tricks/serverless/blob/0cf3b23efdea5cc3f18ee25e87d9f5626990ac08/src/content/realtime/appsync.md), I think) and Google Cloud Functions ([here](https://github.com/CSS-Tricks/serverless/blob/master/src/content/functions/google-cloud-functions.md)) seem to be missing.

I poked around in their respective file histories and I couldn't find old versions of 'em, not sure if they were ever added to begin with.

Happy to PR this if it's just a matter of finding those logos in whatever file format (looks like some are svg and some png?)

**Comment by chriscoyier** [comment]
hopefully that does it. Looks like we had "amplify" logos but not "appsync" and it all kinda came it at once and got confusing
