### ISSUE TITLE
Sub-menus sometimes dont show up

### ISSUE THREAD

**Issue by Darkle** [CSS-Tricks/serverless#72]
Hi, if I browse to https://serverless.css-tricks.com/ and then click on Services, it goes to the https://serverless.css-tricks.com/services/major page and shows the Services sub menu on the right with Could Functions, Auth, Forms etc., but if i browse to the https://serverless.css-tricks.com/services/major page directly, the Services submenu doesnt show up.

**Comment by chriscoyier** [comment]
Simplified all this and shouldn't be an issue anymore.
