### ISSUE TITLE
The same description for different cards

### ISSUE THREAD

**Issue by in-in** [CSS-Tricks/serverless#98]
![200181579333414](https://user-images.githubusercontent.com/8797432/72660480-c5f6d680-39df-11ea-91c9-8e9a8a8d5315.png)

https://serverless.css-tricks.com/resources/

**Comment by chriscoyier** [comment]
ooops! Thanks.

Fixed in https://github.com/CSS-Tricks/serverless/commit/9338c6e08f98e076e90aa2f2d3f27fafd7de6201
